### ISSUE TITLE
Research substrate

### ISSUE THREAD

**Issue by mohanson** [cryptape/muta#2]
- [x] details about substrate wasm runtime: See http://accu.cc/content/bc/substrate_wasm_runtime
- [ ] details about polkadot

**Comment by mohanson** [comment]
> 推荐阅读:  https://cryptape.quip.com/3Q3DAyB8vLR4/Substrate-wasm-runtime-

substrate 的 wasm 运行时模糊了状态转换函数与智能合约的概念, 我们在使用 evm 虚拟机的大前提下, 强行使用 substrate 的 wasm runtime 设计思路没有甚么必要性.

部分开发者为什么想要框架而不是产品? 因为框架可以带来灵活性. 我们之前有过讨论: CITA 的用户拿到 CITA 后做了哪些魔改? 我觉得可以从这方面入手设计我们自己的 wasm runtime. 我的一个初步想法是:

Step1: **验证可行性. 在 CITA1.0(the forked) 的代码上使用 wasm 实现 CITA 的两种经济模型, 经济模型以外部挂载 wasm 方式而非通过修改配置文件方式接入 CITA1.0.**
Step2: To be continued.

希望大家给些意见.
@u2 @yejiayu @zeroqn @keroro520  @kaikai1024 @ouwenkg

**Comment by ouwenkg** [comment]
那我们可以把系统合约拿出去吗

**Comment by u2** [comment]
我个人能想到的自定义需求的只有经济模型，而且这个功能我理解是可以用evm来实现的。我觉得对于cita的系统合约的这种方式和wasm这种方式，都是自定义业务逻辑，wasm我理解可能更灵活，能做的事情更多。wasm更多的是给框架带来灵活性，但是具体的用户场景我也没有想到。

**Comment by kaikai1024** [comment]
> 那我们可以把系统合约拿出去吗，系统合约包含的配置项更加丰富一些。

系统合约和 genesis 文件有关，genesis 外部挂载可以讨论一下，只是 submodule 没什么意义

**Comment by yangby-cryptape** [comment]
### Small Rant

**As a community member, not one of the core team, I can not read that link.**

Since we want to build a community and attract developers from the community.
May be we need a better way to express our opinions.
(If it is a private article, just spread it in a private channel.)

Ref: [CITA PR-189: 这个开源版本，是不是故意把注释删了？](https://github.com/cryptape/cita/issues/189)

**Comment by mohanson** [comment]
I have updated the article on [http://accu.cc/content/bc/substrate_wasm_runtime](http://accu.cc/content/bc/substrate_wasm_runtime)

**Comment by yejiayu** [comment]
> substrate 的 wasm 运行时模糊了状态转换函数与智能合约的概念, 我们在使用 evm 虚拟机的大前提下, 强行使用 substrate 的 wasm runtime 设计思路没有甚么必要性.

我们的 wasm runtime 和 substrate 或者 EVM 要做的事情根本不在一个层面上，没什么对比性。
